# Copyright 2026 The Bazel Authors. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http:#www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""Utilities for applying and reverting synthetic incremental patches."""

import contextlib
import os
import secrets
import subprocess
import tempfile
import utils.logger as logger


def _run_git(args, cwd):
  """Runs a git command, raising RuntimeError with git's stderr on failure."""
  proc = subprocess.run(
      ['git'] + args,
      cwd=cwd,
      stdout=subprocess.DEVNULL,
      stderr=subprocess.PIPE,
      text=True)
  if proc.returncode != 0:
    raise RuntimeError('`git %s` failed in %s (exit code %d):\n%s' %
                       (' '.join(args), cwd, proc.returncode, proc.stderr.strip()))


@contextlib.contextmanager
def apply_patch(project_path, patch_file):
  """Applies patch_file to project_path, replacing __RANDOM_TOKEN__ with a 32-char token.

  On exit, exactly the applied changes are reverted by reverse-applying the same
  (token-substituted) patch. Other modifications and untracked files in the
  project (e.g. files generated by env_configure) are left untouched.

  Args:
    project_path: Path to the root of the Git project repository.
    patch_file: Path to the patch/diff file, or None.

  Yields:
    The generated 32-character random token string if patch_file was applied, else None.
  """
  if not patch_file:
    yield None
    return

  if not os.path.isabs(patch_file):
    patch_file = os.path.abspath(patch_file)

  if not os.path.exists(patch_file):
    raise FileNotFoundError('Patch file not found: %s' % patch_file)

  with open(patch_file, 'r') as pf:
    patch_content = pf.read()

  token = secrets.token_hex(16)
  customized_patch = patch_content.replace('__RANDOM_TOKEN__', token)

  with tempfile.NamedTemporaryFile('w', delete=False, suffix='.patch') as tf:
    tf.write(customized_patch)
    temp_patch_path = tf.name

  try:
    logger.log('Applying patch %s with random token %s' % (patch_file, token))
    # `git apply` is atomic: if it fails, nothing was changed and there is
    # nothing to revert.
    _run_git(['apply', '--whitespace=nowarn', temp_patch_path], project_path)
    try:
      yield token
    finally:
      logger.log('Reverting patch %s in %s...' % (patch_file, project_path))
      _run_git(['apply', '-R', '--whitespace=nowarn', temp_patch_path], project_path)
  finally:
    os.remove(temp_patch_path)
