# Copyright 2026 The Bazel Authors. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http:#www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""Tests for utils/patch.py."""

import os
import shutil
import subprocess
import tempfile
import unittest

from utils import patch


class PatchTest(unittest.TestCase):

  def setUp(self):
    self.temp_dir = tempfile.mkdtemp()
    self.repo_dir = os.path.join(self.temp_dir, 'repo')
    os.makedirs(self.repo_dir)

    # Initialize a clean git repository
    subprocess.run(['git', 'init'], cwd=self.repo_dir, check=True, stdout=subprocess.DEVNULL)
    subprocess.run(['git', 'config', 'user.email', 'test@example.com'], cwd=self.repo_dir, check=True)
    subprocess.run(['git', 'config', 'user.name', 'Test User'], cwd=self.repo_dir, check=True)

    # Commit an initial file
    self.file_path = os.path.join(self.repo_dir, 'lib.cc')
    with open(self.file_path, 'w') as f:
      f.write('const char* TOKEN = "ORIGINAL";\n')

    subprocess.run(['git', 'add', '.'], cwd=self.repo_dir, check=True)
    subprocess.run(['git', 'commit', '-m', 'Initial commit'], cwd=self.repo_dir, check=True, stdout=subprocess.DEVNULL)

  def tearDown(self):
    shutil.rmtree(self.temp_dir)

  def test_apply_patch_none(self):
    with patch.apply_patch(self.repo_dir, None) as token:
      self.assertIsNone(token)
    with open(self.file_path, 'r') as f:
      self.assertEqual('const char* TOKEN = "ORIGINAL";\n', f.read())

  def test_apply_patch_missing_file(self):
    with self.assertRaises(FileNotFoundError):
      with patch.apply_patch(self.repo_dir, '/nonexistent/patch.diff'):
        pass

  def test_apply_patch_with_random_token(self):
    patch_diff = """diff --git a/lib.cc b/lib.cc
--- a/lib.cc
+++ b/lib.cc
@@ -1 +1 @@
-const char* TOKEN = "ORIGINAL";
+const char* TOKEN = "__RANDOM_TOKEN__";
"""
    patch_path = os.path.join(self.temp_dir, 'change.patch')
    with open(patch_path, 'w') as pf:
      pf.write(patch_diff)

    with patch.apply_patch(self.repo_dir, patch_path) as token:
      self.assertIsNotNone(token)
      self.assertEqual(32, len(token))
      with open(self.file_path, 'r') as f:
        content = f.read()
      self.assertIn(token, content)
      self.assertNotIn('__RANDOM_TOKEN__', content)

    # Check that after exiting, the file was reverted
    with open(self.file_path, 'r') as f:
      restored_content = f.read()
    self.assertEqual('const char* TOKEN = "ORIGINAL";\n', restored_content)

    # Check git status is clean
    res = subprocess.run(['git', 'status', '--porcelain'], cwd=self.repo_dir, capture_output=True, text=True, check=True)
    self.assertEqual('', res.stdout.strip())

  def _write_token_patch(self):
    patch_diff = """diff --git a/lib.cc b/lib.cc
--- a/lib.cc
+++ b/lib.cc
@@ -1 +1 @@
-const char* TOKEN = "ORIGINAL";
+const char* TOKEN = "__RANDOM_TOKEN__";
"""
    patch_path = os.path.join(self.temp_dir, 'change.patch')
    with open(patch_path, 'w') as pf:
      pf.write(patch_diff)
    return patch_path

  def test_revert_preserves_untracked_and_unrelated_changes(self):
    # e.g. files generated by env_configure, or local edits to other files.
    untracked = os.path.join(self.repo_dir, 'generated.bazelrc')
    with open(untracked, 'w') as f:
      f.write('build --config=foo\n')
    other = os.path.join(self.repo_dir, 'other.cc')
    with open(other, 'w') as f:
      f.write('int x = 1;\n')
    subprocess.run(['git', 'add', 'other.cc'], cwd=self.repo_dir, check=True)
    subprocess.run(['git', 'commit', '-m', 'other'], cwd=self.repo_dir, check=True,
                   stdout=subprocess.DEVNULL)
    with open(other, 'w') as f:
      f.write('int x = 2;\n')

    with patch.apply_patch(self.repo_dir, self._write_token_patch()):
      pass

    self.assertTrue(os.path.exists(untracked))
    with open(other) as f:
      self.assertEqual('int x = 2;\n', f.read())
    with open(self.file_path) as f:
      self.assertEqual('const char* TOKEN = "ORIGINAL";\n', f.read())

  def test_apply_failure_reports_git_error_and_leaves_tree_alone(self):
    with open(self.file_path, 'w') as f:
      f.write('something else\n')
    with self.assertRaisesRegex(RuntimeError, 'git apply'):
      with patch.apply_patch(self.repo_dir, self._write_token_patch()):
        self.fail('Body must not run when the patch does not apply.')
    with open(self.file_path) as f:
      self.assertEqual('something else\n', f.read())


if __name__ == '__main__':
  unittest.main()
